export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  geminiApiUrl: process.env.GEMINI_API_URL ?? "https://generativelanguage.googleapis.com/v1beta/openai",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  geminiModel: process.env.GEMINI_MODEL ?? "gemini-3.6-flash",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? "",
  fredApiKey: process.env.FRED_API_KEY ?? "",
  twelveDataApiKey: process.env.TWELVE_DATA_API_KEY ?? "",
  twelveDataApiKeySlots: [
    process.env.TWELVE_DATA_API_KEY,
    process.env.TWELVE_DATA_API_KEY_2,
    process.env.TWELVE_DATA_API_KEY_3,
    process.env.TWELVE_DATA_API_KEY_4,
    process.env.TWELVE_DATA_API_KEY_5,
    process.env.TWELVE_DATA_API_KEY_6,
    process.env.TWELVE_DATA_API_KEY_7,
    process.env.TWELVE_DATA_API_KEY_8,
  ],
  twelveDataApiKeys: [
    process.env.TWELVE_DATA_API_KEY,
    process.env.TWELVE_DATA_API_KEY_2,
    process.env.TWELVE_DATA_API_KEY_3,
    process.env.TWELVE_DATA_API_KEY_4,
    process.env.TWELVE_DATA_API_KEY_5,
    process.env.TWELVE_DATA_API_KEY_6,
    process.env.TWELVE_DATA_API_KEY_7,
    process.env.TWELVE_DATA_API_KEY_8,
  ].filter((key): key is string => Boolean(key)),
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramChatId: process.env.TELEGRAM_CHAT_ID ?? "",
  telegramGroupChatId: process.env.TELEGRAM_BTC_GROUP_CHAT_ID ?? "",
  telegramWebhookSecret: process.env.TELEGRAM_WEBHOOK_SECRET ?? "",
  externalScannerTriggerSecret: process.env.EXTERNAL_SCANNER_TRIGGER_SECRET ?? "",
  telegramAssetBots: {
    "EUR/USD": { token: process.env.TELEGRAM_EURUSD_BOT_TOKEN ?? "", chatId: process.env.TELEGRAM_EURUSD_CHAT_ID ?? "", groupChatId: process.env.TELEGRAM_EURUSD_GROUP_CHAT_ID ?? "" },
    "XAU/USD": { token: process.env.TELEGRAM_XAUUSD_BOT_TOKEN ?? "", chatId: process.env.TELEGRAM_XAUUSD_CHAT_ID ?? "", groupChatId: process.env.TELEGRAM_XAUUSD_GROUP_CHAT_ID ?? "" },
    "GBP/USD": { token: process.env.TELEGRAM_GBPUSD_BOT_TOKEN ?? "", chatId: process.env.TELEGRAM_GBPUSD_CHAT_ID ?? "", groupChatId: process.env.TELEGRAM_GBPUSD_GROUP_CHAT_ID ?? "" },
  },
  frontendOrigin: process.env.FRONTEND_ORIGIN ?? "",
};
